# -*- coding: utf-8 -*-
"""ДЗ_5 Михайлов  С.Е

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dxhz3mtz-A4KK5e7pQ16DzoZcYAf7k6

# Домашнее задание №5 — Классы и объекты (ООП)

В этом ноутбуке реализованы классы `Account` и `CreditAccount` в соответствии с требованиями задания, а также приведены примеры их использования.

## Реализация классов `Account` и `CreditAccount`

- `Account` моделирует обычный банковский счёт, хранит историю операций и текущий баланс.
- `CreditAccount(Account)` наследует все возможности `Account` и добавляет кредитный лимит, а также признак использования кредитных средств в истории операций.
"""

from datetime import datetime


class Account:
    """Класс, моделирующий обычный банковский счёт."""

    def __init__(self, account_holder: str, balance: float = 0.0) -> None:
        """Инициализация счёта.

        :param account_holder: имя владельца счёта
        :param balance: начальный баланс (не может быть отрицательным)
        """
        if balance < 0:
            raise ValueError('Начальный баланс не может быть отрицательным')

        self.holder = account_holder
        self._balance = float(balance)
        self.operations_history: list[dict] = []

    def _add_operation(self, op_type: str, amount: float, status: str) -> None:
        """Внутренний метод: добавляет запись об операции в историю."""
        record = {
            'type': op_type,
            'amount': float(amount),
            'datetime': datetime.now(),
            'balance_after': self._balance,
            'status': status,
        }
        self.operations_history.append(record)

    def deposit(self, amount: float) -> bool:
        """Пополнение счёта.

        :param amount: сумма пополнения (должна быть > 0)
        :return: True, если операция успешна, False — если нет
        """
        if amount <= 0:
            self._add_operation('deposit', amount, 'fail')
            return False

        self._balance += amount
        self._add_operation('deposit', amount, 'success')
        return True

    def withdraw(self, amount: float) -> bool:
        """Снятие средств со счёта.

        :param amount: сумма снятия (должна быть > 0)
        :return: True, если операция успешна, False — если нет
        """
        if amount <= 0:
            self._add_operation('withdraw', amount, 'fail')
            return False

        if amount > self._balance:
            self._add_operation('withdraw', amount, 'fail')
            return False

        self._balance -= amount
        self._add_operation('withdraw', amount, 'success')
        return True

    def get_balance(self) -> float:
        """Возвращает текущий баланс счёта."""
        return self._balance

    def get_history(self) -> list[dict]:
        """Возвращает копию истории операций."""
        return self.operations_history.copy()


class CreditAccount(Account):
    """Кредитный счёт, наследующий функциональность обычного счёта."""

    def __init__(self, account_holder: str, balance: float = 0.0, credit_limit: float = 0.0) -> None:
        """Инициализация кредитного счёта.

        :param account_holder: имя владельца
        :param balance: начальный баланс (>= 0)
        :param credit_limit: кредитный лимит (>= 0)
        """
        super().__init__(account_holder, balance)

        if credit_limit < 0:
            raise ValueError('Кредитный лимит не может быть отрицательным')

        self.credit_limit = float(credit_limit)

    def _add_operation(self, op_type: str, amount: float, status: str, used_credit: bool = False) -> None:
        """Добавляет запись об операции с учётом использования кредитных средств."""
        record = {
            'type': op_type,
            'amount': float(amount),
            'datetime': datetime.now(),
            'balance_after': self._balance,
            'status': status,
            'used_credit': used_credit,
        }
        self.operations_history.append(record)

    def get_available_credit(self) -> float:
        """Возвращает доступный размер кредитных средств."""
        return self._balance + self.credit_limit

    def deposit(self, amount: float) -> bool:
        """Пополнение кредитного счёта."""
        if amount <= 0:
            self._add_operation('deposit', amount, 'fail', used_credit=self._balance < 0)
            return False

        self._balance += amount
        used_credit = self._balance < 0
        self._add_operation('deposit', amount, 'success', used_credit=used_credit)
        return True

    def withdraw(self, amount: float) -> bool:
        """Снятие средств с учётом кредитного лимита."""
        if amount <= 0:
            self._add_operation('withdraw', amount, 'fail', used_credit=self._balance < 0)
            return False

        new_balance = self._balance - amount
        if new_balance < -self.credit_limit:
            self._add_operation('withdraw', amount, 'fail', used_credit=True)
            return False

        self._balance = new_balance
        used_credit = self._balance < 0
        self._add_operation('withdraw', amount, 'success', used_credit=used_credit)
        return True

"""## Примеры использования классов

Ниже приведены примеры работы с `Account` и `CreditAccount` для самопроверки.
"""

# Пример работы обычного счёта
acc = Account('Иван Иванов', balance=1000)

acc.deposit(500)
acc.withdraw(300)
acc.withdraw(5000)  # неуспешная операция: недостаточно средств
acc.deposit(-100)   # неуспешная операция: отрицательная сумма

print('Баланс обычного счёта:', acc.get_balance())
print('\nИстория операций для обычного счёта:')
for op in acc.get_history():
    print(op)

print('\n' + '=' * 60 + '\n')

# Пример работы кредитного счёта
credit_acc = CreditAccount('Пётр Петров', balance=0, credit_limit=5000)

credit_acc.withdraw(3000)  # используем кредит
credit_acc.withdraw(2500)  # попытка превысить лимит, должна быть неуспешной
credit_acc.deposit(1000)   # частично погашаем задолженность

print('Баланс кредитного счёта:', credit_acc.get_balance())
print('Доступный кредит:', credit_acc.get_available_credit())

print('\nИстория операций для кредитного счёта:')
for op in credit_acc.get_history():
    print(op)